### ISSUE TITLE
Configurable tolerations

### ISSUE THREAD

**Issue by PatTheSilent** [letsbuilders/jsonnet-libs#65]
We're forced to have a taint on spot instances on Azure clusters:

```yaml
taints:
  - key: kubernetes.azure.com/scalesetpriority
    value: spot
    effect: NoSchedule
```
This means that if we want to run Pods on those the pods need to tolerate that taint. We want to run our Pods on spot instances as much as we can to save costs. Because our library doesn't currently support setting tolerations or affinities we add them to deployments by overriding them like [here](https://github.com/letsbuilders/aproplan-tiling-worker/blob/master/deploy/lib/letsbuilders/main.libsonnet#L25). This is a very crude approach and we should rather have it configurable with options defined in the `_config` object. 

TODO:
* add support for configuring tolerations
* update all services that currently use overrides
